# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x05myapi\x1a\x1bgoogle/protobuf/empty.proto\"G\n\x07Usuario\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05idade\x18\x03 \x01(\x05\x12\x13\n\x0bid_playlist\x18\x04 \x03(\x05\"3\n\x06Musica\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0f\n\x07\x61rtista\x18\x03 \x01(\t\"K\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x12\n\nid_usuario\x18\x03 \x01(\x05\x12\x11\n\tid_musica\x18\x04 \x03(\x05\"\x0e\n\x0c\x45mptyMessage2\xd7\x02\n\x05MyApi\x12\x30\n\x0c\x43riarUsuario\x12\x0e.myapi.Usuario\x1a\x0e.myapi.Usuario\"\x00\x12<\n\x0eListarUsuarios\x12\x16.google.protobuf.Empty\x1a\x0e.myapi.Usuario\"\x00\x30\x01\x12-\n\x0b\x43riarMusica\x12\r.myapi.Musica\x1a\r.myapi.Musica\"\x00\x12:\n\rListarMusicas\x12\x16.google.protobuf.Empty\x1a\r.myapi.Musica\"\x00\x30\x01\x12\x33\n\rCriarPlaylist\x12\x0f.myapi.Playlist\x1a\x0f.myapi.Playlist\"\x00\x12>\n\x0fListarPlaylists\x12\x16.google.protobuf.Empty\x1a\x0f.myapi.Playlist\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USUARIO._serialized_start=49
  _USUARIO._serialized_end=120
  _MUSICA._serialized_start=122
  _MUSICA._serialized_end=173
  _PLAYLIST._serialized_start=175
  _PLAYLIST._serialized_end=250
  _EMPTYMESSAGE._serialized_start=252
  _EMPTYMESSAGE._serialized_end=266
  _MYAPI._serialized_start=269
  _MYAPI._serialized_end=612
# @@protoc_insertion_point(module_scope)
