# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api_pb2 as api__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class MyApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarUsuario = channel.unary_unary(
                '/myapi.MyApi/CriarUsuario',
                request_serializer=api__pb2.Usuario.SerializeToString,
                response_deserializer=api__pb2.Usuario.FromString,
                )
        self.ListarUsuarios = channel.unary_stream(
                '/myapi.MyApi/ListarUsuarios',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=api__pb2.Usuario.FromString,
                )
        self.CriarMusica = channel.unary_unary(
                '/myapi.MyApi/CriarMusica',
                request_serializer=api__pb2.Musica.SerializeToString,
                response_deserializer=api__pb2.Musica.FromString,
                )
        self.ListarMusicas = channel.unary_stream(
                '/myapi.MyApi/ListarMusicas',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=api__pb2.Musica.FromString,
                )
        self.CriarPlaylist = channel.unary_unary(
                '/myapi.MyApi/CriarPlaylist',
                request_serializer=api__pb2.Playlist.SerializeToString,
                response_deserializer=api__pb2.Playlist.FromString,
                )
        self.ListarPlaylists = channel.unary_stream(
                '/myapi.MyApi/ListarPlaylists',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=api__pb2.Playlist.FromString,
                )


class MyApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CriarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarMusicas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPlaylists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarUsuario,
                    request_deserializer=api__pb2.Usuario.FromString,
                    response_serializer=api__pb2.Usuario.SerializeToString,
            ),
            'ListarUsuarios': grpc.unary_stream_rpc_method_handler(
                    servicer.ListarUsuarios,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=api__pb2.Usuario.SerializeToString,
            ),
            'CriarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarMusica,
                    request_deserializer=api__pb2.Musica.FromString,
                    response_serializer=api__pb2.Musica.SerializeToString,
            ),
            'ListarMusicas': grpc.unary_stream_rpc_method_handler(
                    servicer.ListarMusicas,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=api__pb2.Musica.SerializeToString,
            ),
            'CriarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarPlaylist,
                    request_deserializer=api__pb2.Playlist.FromString,
                    response_serializer=api__pb2.Playlist.SerializeToString,
            ),
            'ListarPlaylists': grpc.unary_stream_rpc_method_handler(
                    servicer.ListarPlaylists,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=api__pb2.Playlist.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myapi.MyApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapi.MyApi/CriarUsuario',
            api__pb2.Usuario.SerializeToString,
            api__pb2.Usuario.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/myapi.MyApi/ListarUsuarios',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            api__pb2.Usuario.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CriarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapi.MyApi/CriarMusica',
            api__pb2.Musica.SerializeToString,
            api__pb2.Musica.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListarMusicas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/myapi.MyApi/ListarMusicas',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            api__pb2.Musica.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CriarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapi.MyApi/CriarPlaylist',
            api__pb2.Playlist.SerializeToString,
            api__pb2.Playlist.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListarPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/myapi.MyApi/ListarPlaylists',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            api__pb2.Playlist.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
